### ISSUE TITLE
Spotify v 1.0

### ISSUE THREAD

**Issue by yoshadow** [olejon/spotcommander#100]
Hi!!!

I followed the instructions to install spotify and everything works well, but when I start the spotcommander app on mi smartphone it says that I have de beta version of Spotify on my computer, and its not supprted yet. Do I have to wait for an update of spotcommander? or I can install a previous version of spotify on my computer?.

Greetings.

**SOLUTION:** [See my comment](https://github.com/olejon/spotcommander/issues/100#issuecomment-309279828).

**Comment by olejon** [comment]
Can you just check that you in fact have the beta version? Take a screenshot and I can tell you.

**Comment by changeableface** [comment]
This has worked in the office for several months, however when I came in this morning i'm greeted with the same error on the web client, so I assume spotify must have updated over night?

Version number: Spotify version 1.0.23.93.gd6cfae15

**Comment by olejon** [comment]
Yup, seems like Spotify has pushed v 1.0 to the official repo now. Due to a bug this does not work with SpotCommander (yet at least). You can easily install the previous version by following this guide on the SpotCommander wiki:

https://github.com/olejon/spotcommander/wiki/DowngradeSpotify

Install the Spotify 0.9.17.8 package.

**Comment by yoshadow** [comment]
Thank you all.
I'm really 
![spotify](https://cloud.githubusercontent.com/assets/11691371/13613751/0da8944c-e533-11e5-8863-f37c456fbdc9.png)
sorry I didn't answer you before, I have the 1.0.XXX version.
This is the screenshot, I'll try installing previous version. Thanks again !!! =D

**Comment by TheAppService** [comment]
Any news on this ?

**Comment by olejon** [comment]
Not as long as I can not find a way to get PlaybackStatus through D-Bus. It just times out. Any help is appreciated. This is something that has worked at least since Spotify v 0.6, so they seem to have broken the MPRIS spec with v 1.0.

Just downgrade to 0.9.17.8. Works just as good (Spotify Connect as well).

https://github.com/olejon/spotcommander/wiki/DowngradeSpotify

**Comment by olejon** [comment]
In fact the broken D-Bus MPRIS implementation is well known to the Spotify developers, but they are slow when it comes to fixing Linux-specific stuff, unfortunately:

https://community.spotify.com/t5/Help-Desktop-Linux-Windows-Web/Linux-Spotify-client-1-x-now-in-stable/td-p/1300404

Fix is still to install the version needed by SpotCommander:
https://github.com/olejon/spotcommander/wiki/DowngradeSpotify

**Comment by olejon** [comment]
Spotify v 1.0 is partially supported from SpotCommander v 12.6 and newer. More to come.

**Comment by keunes** [comment]
Users over at the [Spotify forum](https://community.spotify.com/t5/Help-Desktop-Linux-Windows-Web/SOLVED-Linux-Spotify-DBus-MPRIS2-support-not-fully-working/td-p/1208249/page/3) have claimed that the issue has been solved. Does it mean that now some work needs to be done on Spotcommander's side? Or is the issue Spotcommander has slightly different from the issue I linked to in the Spotify forums?

**Comment by olejon** [comment]
No, they are just happy because retrieving metadata works again and you can do basic playback control. The problem is the OpenUri does not behave as before.

**Comment by keunes** [comment]
> No, they are just happy because retrieving metadata works again and you can do basic playback control. The problem is that OpenUri does not behave as before.

As that issue has been marked as 'solved', should we create a new issue so that Spotcommander's problem gets a bit of special attention?

**Comment by olejon** [comment]
@keunes It is actually not considered a bug by Spotify. You can see their argument in this post: https://community.spotify.com/t5/Help-Desktop-Linux-Windows-Web/SOLVED-Linux-Spotify-DBus-MPRIS2-support-not-fully-working/m-p/1323359/highlight/true#M154662

I have suggested that it could behave as before if you run Pause() first, as is necessary today with version 1.0 to play a track, or else it just opens the album. Or at least we should be able to run Stop() and after that OpenUri could behave normally, Stop() is not used by Spotify in any way I know, but it works (I'm talking about D-Bus MPRIS here).

**Comment by f69m** [comment]
OpenURI behaves much better in the latest stable version 1.0.37. Playing albums and playlists works fine as before, no need to call Pause() first. Time to get rid of some of the extra code and some of the JS "Spotify Warning"?

Still need the "killall" work-around for quitting and play_uri_from_playlist is still broken.

Running "spotify --version" allows to check, if the latest version is installed. Just don't run it with 0.9 installed, as that launches Spotify.

**Comment by olejon** [comment]
Thanks for your useful feedback. I'll look into it when my illness (hopefully) improves!

**Comment by olejon** [comment]
@f69m Now there is this bug where playing a track with `OpenUri` and then playing next track with `Next` just plays the track currently playing again. This does not trigger the PHP queue script in the BASH script `bin/spotcommander-queue` because the metadata has not changed. That check is there to not cause the next track to play if one choose to start the track over again for instance. Commenting line 28 and 34 fixes that but causes the next track in the queue to play if one has listened to a track for 30 seconds for instance and then press Previous... Any better workaround would be nice.

**Comment by olejon** [comment]
Current problems with SpotCommander v 12.9:

* Playing a single track will repeat it over and over
* Manually skipping to the next track will in many cases not play queued tracks, because of the above problem - *possible solution: play an artist, album or playlist and it could work as normal*
* Starting track radios does not work
* Manually playing local files does not work, but play in playlists

Please report additional problems, if any.

**Comment by olejon** [comment]
If you are a *Spotify Premium user*, the latest version of SpotCommander, v 13.2, supports Spotify v 1.0 good, and with *many new features* for those.

For *Spotify Free users* it is still recommended to use [version 0.9 of Spotify](http://www.olejon.net/code/spotcommander/?downgrade_spotify).

**Comment by olejon** [comment]
The wiki has been updated with enough details about this.
